replicaCount: 3

image:
  repository: ""        # Wird in Jenkins gesetzt
  pullPolicy: IfNotPresent
  tag: ""               # Wird in Jenkins gesetzt

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ""              # Wichtig: leer, Jenkins setzt den Typ (z. B. NodePort)
  port: 80
  targetPort: 8000
  nodePort: 0           # Platzhalter, wird in Jenkins überschrieben

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
