replicaCount: 3

image:
  repository: "dummy"
  pullPolicy: IfNotPresent
  tag: "dummy"

imagePullSecrets:
  - name: "regcred"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP  # Wird von Jenkinsfile für prod auf NodePort gesetzt
  port: 80
  targetPort: 8000
  # nodePort wird nur per Jenkinsfile bei Bedarf gesetzt

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
